[package]
name = "flux-ai"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
config = { version = "0.14", default-features = false, features = ["toml"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
uuid = { version = "1.10.0", features = ["serde", "v7"] }
cloudevents-sdk = { version = "0.7.0", features = ["nats"] }
futures-lite = "2.3.0"

async-nats = "0.36.0"

axum = "0.7.5"

tokio = { version = "1.40.0", features = ["full"] }

prost = "0.13.2"
chrono = "0.4.38"

