services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    command: "uvicorn main:app --host 0.0.0.0 --port 3000 --reload"
    environment:
      TF_MODEL: knkarthick/MEETING_SUMMARY
      HISTFILE: /app/.local/.bash_history
    networks:
      default:
        aliases:
          - flux-ai.flux.local
    ports:
      - 3092:3000
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - transformers-cache:/root/.cache/huggingface/hub

volumes:
  transformers-cache:

networks:
  default:
    name: flux-dev
