_name = "flux-ai"

[http]
endpoint = "0.0.0.0:3000"

[ollama]
endpoint = "http://0.0.0.0:11434"
instruction = "Суммаризируй диалог в 20 слов используя имена:\n"

[redis]
endpoint = "redis://0.0.0.0:6379"

[nats]
endpoint = "0.0.0.0:4222"

[streams.messaging]
name = "flux"
consumer = "flux-ai"

[streams.messaging.subjects]
request = "flux.streams.summarize.request"
response = "flux.streams.summarize.response"

[streams.kv]
name = "streams-summarize-queue"

[streams.execution]
period_ms = 5_000
batch_size = 2

# [clients.flux_auth]
# endpoint = "http://0.0.0.0:3000"

# [clients.flux_core]
# endpoint = "http://0.0.0.0:3000"
